import OpenAI from "openai";
const openai = new OpenAI();

// 1. Define a list of callable tools for the model
const tools: OpenAI.Responses.Tool[] = [
  {
    type: "function",
    name: "get_horoscope",
    description: "Get today's horoscope for an astrological sign.",
    parameters: {
      type: "object",
      properties: {
        sign: {
          type: "string",
          description: "An astrological sign like Taurus or Aquarius",
        },
      },
      required: ["sign"],
    },
    strict: false,
  },
];

let input_list: any[] = [];

function getHoroscope(sign: string) {
  return sign + " Next Tuesday you will befriend a baby otter.";
}

// Create a running input list we will add to over time
let input: OpenAI.Responses.ResponseInput = [
  { role: "user", content: "What is my horoscope? I am an Aquarius." },
];

// 2. Prompt the model with tools defined
let response = await openai.responses.create({
  model: "gpt-5",
  tools,
  input,
});

response.output.forEach((item) => {
  if (item.type == "function_call") {
    if (item.name == "get_horoscope") {
      // 3. Execute the function logic for get_horoscope
      const horoscope = getHoroscope(JSON.parse(item.arguments));

      // 4. Provide function call results to the model
      input_list.push({
        type: "function_call_output",
        call_id: item.call_id,
        output: JSON.stringify({
          horoscope,
        }),
      });
    }
  }
});

console.log("Final input:");
console.log(JSON.stringify(input, null, 2));

response = await openai.responses.create({
  model: "gpt-5",
  instructions: "Respond only with a horoscope generated by a tool.",
  tools,
  input,
});

// 5. The model should be able to give a response!
console.log("Final output:");
console.log(JSON.stringify(response.output, null, 2));
